<?php

/**
 * Code generated by thesis/protoc-plugin. DO NOT EDIT.
 * Versions:
 *   thesis/protoc-plugin — v0.1.22
 *   protoc               — v6.33.5
 * Source: google/rpc/error_details.proto
 */

declare(strict_types=1);

namespace Google\Rpc\Help;

use Thesis\Protobuf\Reflection;

/**
 * @api
 *
 * Describes a URL link.
 */
final readonly class Link
{
    /**
     * @param string $description Describes what the link offers.
     * @param string $url The URL of the link.
     */
    public function __construct(
        #[Reflection\Field(1, Reflection\StringT::T)]
        public string $description = '',
        #[Reflection\Field(2, Reflection\StringT::T)]
        public string $url = '',
    ) {}
}
