<?php

/**
 * Code generated by thesis/protoc-plugin. DO NOT EDIT.
 * Versions:
 *   thesis/protoc-plugin — v0.3.0
 *   protoc               — v6.33.5
 * Source: google/rpc/error_details.proto
 */

declare(strict_types=1);

namespace Google\Rpc\BadRequest;

use Thesis\Protobuf\Reflection;

/**
 * @api
 *
 * A message type used to describe a single bad request field.
 */
final readonly class FieldViolation
{
    /**
     * @param string $field A path that leads to a field in the request body. The value will be a
     * sequence of dot-separated identifiers that identify a protocol buffer
     * field.
     *
     * Consider the following:
     *
     *     message CreateContactRequest {
     *       message EmailAddress {
     *         enum Type {
     *           TYPE_UNSPECIFIED = 0;
     *           HOME = 1;
     *           WORK = 2;
     *         }
     *
     *         optional string email = 1;
     *         repeated EmailType type = 2;
     *       }
     *
     *       string full_name = 1;
     *       repeated EmailAddress email_addresses = 2;
     *     }
     *
     * In this example, in proto `field` could take one of the following values:
     *
     * * `full_name` for a violation in the `full_name` value
     * * `email_addresses[1].email` for a violation in the `email` field of the
     *   first `email_addresses` message
     * * `email_addresses[3].type[2]` for a violation in the second `type`
     *   value in the third `email_addresses` message.
     *
     * In JSON, the same values are represented as:
     *
     * * `fullName` for a violation in the `fullName` value
     * * `emailAddresses[1].email` for a violation in the `email` field of the
     *   first `emailAddresses` message
     * * `emailAddresses[3].type[2]` for a violation in the second `type`
     *   value in the third `emailAddresses` message.
     * @param string $description A description of why the request element is bad.
     * @param string $reason The reason of the field-level error. This is a constant value that
     * identifies the proximate cause of the field-level error. It should
     * uniquely identify the type of the FieldViolation within the scope of the
     * google.rpc.ErrorInfo.domain. This should be at most 63
     * characters and match a regular expression of `[A-Z][A-Z0-9_]+[A-Z0-9]`,
     * which represents UPPER_SNAKE_CASE.
     * @param ?\Google\Rpc\LocalizedMessage $localizedMessage Provides a localized error message for field-level errors that is safe to
     * return to the API consumer.
     */
    public function __construct(
        #[Reflection\Field(1, Reflection\StringT::T)]
        public string $field = '',
        #[Reflection\Field(2, Reflection\StringT::T)]
        public string $description = '',
        #[Reflection\Field(3, Reflection\StringT::T)]
        public string $reason = '',
        #[Reflection\Field(4, new Reflection\ObjectT(\Google\Rpc\LocalizedMessage::class))]
        public ?\Google\Rpc\LocalizedMessage $localizedMessage = null,
    ) {}
}
