<?php

/**
 * Code generated by thesis/protoc-plugin. DO NOT EDIT.
 * Versions:
 *   thesis/protoc-plugin — v0.1.24
 *   protoc               — v6.33.5
 * Source: google/rpc/error_details.proto
 */

declare(strict_types=1);

namespace Google\Rpc\PreconditionFailure;

use Thesis\Protobuf\Reflection;

/**
 * @api
 *
 * A message type used to describe a single precondition failure.
 */
final readonly class Violation
{
    /**
     * @param string $type The type of PreconditionFailure. We recommend using a service-specific
     * enum type to define the supported precondition violation subjects. For
     * example, "TOS" for "Terms of Service violation".
     * @param string $subject The subject, relative to the type, that failed.
     * For example, "google.com/cloud" relative to the "TOS" type would indicate
     * which terms of service is being referenced.
     * @param string $description A description of how the precondition failed. Developers can use this
     * description to understand how to fix the failure.
     *
     * For example: "Terms of service not accepted".
     */
    public function __construct(
        #[Reflection\Field(1, Reflection\StringT::T)]
        public string $type = '',
        #[Reflection\Field(2, Reflection\StringT::T)]
        public string $subject = '',
        #[Reflection\Field(3, Reflection\StringT::T)]
        public string $description = '',
    ) {}
}
