<?php

/**
 * Code generated by thesis/protoc-plugin. DO NOT EDIT.
 * Versions:
 *   thesis/protoc-plugin — v0.4.2
 *   protoc               — v6.33.5
 * Source: google/rpc/error_details.proto
 */

declare(strict_types=1);

namespace Google\Rpc\QuotaFailure;

use Thesis\Protobuf;
use Thesis\Protobuf\Reflection;

/**
 * @api
 *
 * A message type used to describe a single quota violation.  For example, a
 * daily quota or a custom quota that was exceeded.
 */
final readonly class Violation
{
    /**
     * @param string $subject The subject on which the quota check failed.
     * For example, "clientip:<ip address of client>" or "project:<Google
     * developer project id>".
     * @param string $description A description of how the quota check failed. Clients can use this
     * description to find more about the quota configuration in the service's
     * public documentation, or find the relevant quota limit to adjust through
     * developer console.
     *
     * For example: "Service disabled" or "Daily Limit for read operations
     * exceeded".
     * @param string $apiService The API Service from which the `QuotaFailure.Violation` orginates. In
     * some cases, Quota issues originate from an API Service other than the one
     * that was called. In other words, a dependency of the called API Service
     * could be the cause of the `QuotaFailure`, and this field would have the
     * dependency API service name.
     *
     * For example, if the called API is Kubernetes Engine API
     * (container.googleapis.com), and a quota violation occurs in the
     * Kubernetes Engine API itself, this field would be
     * "container.googleapis.com". On the other hand, if the quota violation
     * occurs when the Kubernetes Engine API creates VMs in the Compute Engine
     * API (compute.googleapis.com), this field would be
     * "compute.googleapis.com".
     * @param string $quotaMetric The metric of the violated quota. A quota metric is a named counter to
     * measure usage, such as API requests or CPUs. When an activity occurs in a
     * service, such as Virtual Machine allocation, one or more quota metrics
     * may be affected.
     *
     * For example, "compute.googleapis.com/cpus_per_vm_family",
     * "storage.googleapis.com/internet_egress_bandwidth".
     * @param string $quotaId The id of the violated quota. Also know as "limit name", this is the
     * unique identifier of a quota in the context of an API service.
     *
     * For example, "CPUS-PER-VM-FAMILY-per-project-region".
     * @param Protobuf\Map<string, string> $quotaDimensions The dimensions of the violated quota. Every non-global quota is enforced
     * on a set of dimensions. While quota metric defines what to count, the
     * dimensions specify for what aspects the counter should be increased.
     *
     * For example, the quota "CPUs per region per VM family" enforces a limit
     * on the metric "compute.googleapis.com/cpus_per_vm_family" on dimensions
     * "region" and "vm_family". And if the violation occurred in region
     * "us-central1" and for VM family "n1", the quota_dimensions would be,
     *
     * {
     *   "region": "us-central1",
     *   "vm_family": "n1",
     * }
     *
     * When a quota is enforced globally, the quota_dimensions would always be
     * empty.
     * @param int $quotaValue The enforced quota value at the time of the `QuotaFailure`.
     *
     * For example, if the enforced quota value at the time of the
     * `QuotaFailure` on the number of CPUs is "10", then the value of this
     * field would reflect this quantity.
     * @param ?int $futureQuotaValue The new quota value being rolled out at the time of the violation. At the
     * completion of the rollout, this value will be enforced in place of
     * quota_value. If no rollout is in progress at the time of the violation,
     * this field is not set.
     *
     * For example, if at the time of the violation a rollout is in progress
     * changing the number of CPUs quota from 10 to 20, 20 would be the value of
     * this field.
     */
    public function __construct(
        #[Reflection\Field(1, Reflection\StringT::T)]
        public string $subject = '',
        #[Reflection\Field(2, Reflection\StringT::T)]
        public string $description = '',
        #[Reflection\Field(3, Reflection\StringT::T)]
        public string $apiService = '',
        #[Reflection\Field(4, Reflection\StringT::T)]
        public string $quotaMetric = '',
        #[Reflection\Field(5, Reflection\StringT::T)]
        public string $quotaId = '',
        #[Reflection\Field(6, new Reflection\MapT(Reflection\StringT::T, Reflection\StringT::T))]
        public Protobuf\Map $quotaDimensions = new Protobuf\Map(),
        #[Reflection\Field(7, Reflection\Int64T::T)]
        public int $quotaValue = 0,
        #[Reflection\Field(8, Reflection\Int64T::T)]
        public ?int $futureQuotaValue = null,
    ) {}
}
