<?php

/**
 * Code generated by thesis/protoc-plugin. DO NOT EDIT.
 * Versions:
 *   thesis/protoc-plugin — v0.1.13
 *   protoc               — v6.33.5
 */

declare(strict_types=1);

\Thesis\Protobuf\Pool\Registry::get()->register(
    new \Thesis\Protobuf\Pool\OnceRegistrar(new \Google\Rpc\GoogleRpcStatusDescriptorRegistry()),
    new \Thesis\Protobuf\Pool\OnceRegistrar(new \Google\Rpc\GoogleRpcErrorDetailsDescriptorRegistry()),
    new \Thesis\Protobuf\Pool\OnceRegistrar(new \Google\Rpc\GoogleRpcCodeDescriptorRegistry()),
);
