<?php

/**
 * Code generated by thesis/protoc-plugin. DO NOT EDIT.
 * Versions:
 *   thesis/protoc-plugin — v0.1.21
 *   protoc               — v6.33.5
 * Source: google/rpc/error_details.proto
 */

declare(strict_types=1);

namespace Google\Rpc;

use Thesis\Protobuf\Reflection;

/**
 * @api
 *
 * Describes violations in a client request. This error type focuses on the
 * syntactic aspects of the request.
 */
final readonly class BadRequest
{
    /**
     * @param list<\Google\Rpc\BadRequest\FieldViolation> $fieldViolations Describes all violations in a client request.
     */
    public function __construct(
        #[Reflection\Field(1, new Reflection\ListT(new Reflection\ObjectT(\Google\Rpc\BadRequest\FieldViolation::class)))]
        public array $fieldViolations = [],
    ) {}
}
