<?php

/**
 * Code generated by thesis/protoc-plugin. DO NOT EDIT.
 * Versions:
 *   thesis/protoc-plugin — v0.2.0
 *   protoc               — v6.33.5
 * Source: google/rpc/error_details.proto
 */

declare(strict_types=1);

namespace Google\Rpc;

use Thesis\Protobuf\Reflection;

/**
 * @api
 *
 * Describes additional debugging info.
 */
final readonly class DebugInfo
{
    /**
     * @param list<string> $stackEntries The stack trace entries indicating where the error occurred.
     * @param string $detail Additional debugging information provided by the server.
     */
    public function __construct(
        #[Reflection\Field(1, new Reflection\ListT(Reflection\StringT::T))]
        public array $stackEntries = [],
        #[Reflection\Field(2, Reflection\StringT::T)]
        public string $detail = '',
    ) {}
}
