<?php

/**
 * Code generated by thesis/protoc-plugin. DO NOT EDIT.
 * Versions:
 *   thesis/protoc-plugin — v0.3.0
 *   protoc               — v6.33.5
 * Source: google/rpc/error_details.proto
 */

declare(strict_types=1);

namespace Google\Rpc;

use Thesis\Protobuf\Reflection;

/**
 * @api
 *
 * Provides a localized error message that is safe to return to the user
 * which can be attached to an RPC error.
 */
final readonly class LocalizedMessage
{
    /**
     * @param string $locale The locale used following the specification defined at
     * https://www.rfc-editor.org/rfc/bcp/bcp47.txt.
     * Examples are: "en-US", "fr-CH", "es-MX"
     * @param string $message The localized error message in the above locale.
     */
    public function __construct(
        #[Reflection\Field(1, Reflection\StringT::T)]
        public string $locale = '',
        #[Reflection\Field(2, Reflection\StringT::T)]
        public string $message = '',
    ) {}
}
