<?php

/**
 * Code generated by thesis/protoc-plugin. DO NOT EDIT.
 * Versions:
 *   thesis/protoc-plugin — v0.1.19
 *   protoc               — v6.33.5
 * Source: google/rpc/error_details.proto
 */

declare(strict_types=1);

namespace Google\Rpc;

use Thesis\Protobuf\Reflection;

/**
 * @api
 *
 * Describes what preconditions have failed.
 *
 * For example, if an RPC failed because it required the Terms of Service to be
 * acknowledged, it could list the terms of service violation in the
 * PreconditionFailure message.
 */
final readonly class PreconditionFailure
{
    /**
     * @param list<\Google\Rpc\PreconditionFailure\Violation> $violations Describes all precondition violations.
     */
    public function __construct(
        #[Reflection\Field(1, new Reflection\ListT(new Reflection\ObjectT(\Google\Rpc\PreconditionFailure\Violation::class)))]
        public array $violations = [],
    ) {}
}
