<?php

/**
 * Code generated by thesis/protoc-plugin. DO NOT EDIT.
 * Versions:
 *   thesis/protoc-plugin — v0.3.1
 *   protoc               — v6.33.5
 * Source: google/rpc/error_details.proto
 */

declare(strict_types=1);

namespace Google\Rpc;

use Thesis\Protobuf\Reflection;

/**
 * @api
 *
 * Contains metadata about the request that clients can attach when filing a bug
 * or providing other forms of feedback.
 */
final readonly class RequestInfo
{
    /**
     * @param string $requestId An opaque string that should only be interpreted by the service generating
     * it. For example, it can be used to identify requests in the service's logs.
     * @param string $servingData Any data that was used to serve this request. For example, an encrypted
     * stack trace that can be sent back to the service provider for debugging.
     */
    public function __construct(
        #[Reflection\Field(1, Reflection\StringT::T)]
        public string $requestId = '',
        #[Reflection\Field(2, Reflection\StringT::T)]
        public string $servingData = '',
    ) {}
}
