<?php

/**
 * Code generated by thesis/protoc-plugin. DO NOT EDIT.
 * Versions:
 *   thesis/protoc-plugin — v0.1.20
 *   protoc               — v6.33.5
 * Source: google/rpc/error_details.proto
 */

declare(strict_types=1);

namespace Google\Rpc;

use Thesis\Protobuf\Reflection;

/**
 * @api
 *
 * Describes the resource that is being accessed.
 */
final readonly class ResourceInfo
{
    /**
     * @param string $resourceType A name for the type of resource being accessed, e.g. "sql table",
     * "cloud storage bucket", "file", "Google calendar"; or the type URL
     * of the resource: e.g. "type.googleapis.com/google.pubsub.v1.Topic".
     * @param string $resourceName The name of the resource being accessed.  For example, a shared calendar
     * name: "example.com_4fghdhgsrgh@group.calendar.google.com", if the current
     * error is
     * [google.rpc.Code.PERMISSION_DENIED][google.rpc.Code.PERMISSION_DENIED].
     * @param string $owner The owner of the resource (optional).
     * For example, "user:<owner email>" or "project:<Google developer project
     * id>".
     * @param string $description Describes what error is encountered when accessing this resource.
     * For example, updating a cloud project may require the `writer` permission
     * on the developer console project.
     */
    public function __construct(
        #[Reflection\Field(1, Reflection\StringT::T)]
        public string $resourceType = '',
        #[Reflection\Field(2, Reflection\StringT::T)]
        public string $resourceName = '',
        #[Reflection\Field(3, Reflection\StringT::T)]
        public string $owner = '',
        #[Reflection\Field(4, Reflection\StringT::T)]
        public string $description = '',
    ) {}
}
