<?php

/**
 * Code generated by thesis/protoc-plugin. DO NOT EDIT.
 * Versions:
 *   thesis/protoc-plugin — v0.1.20
 *   protoc               — v6.33.5
 * Source: google/rpc/error_details.proto
 */

declare(strict_types=1);

namespace Google\Rpc;

use Thesis\Protobuf\Reflection;

/**
 * @api
 *
 * Describes when the clients can retry a failed request. Clients could ignore
 * the recommendation here or retry when this information is missing from error
 * responses.
 *
 * It's always recommended that clients should use exponential backoff when
 * retrying.
 *
 * Clients should wait until `retry_delay` amount of time has passed since
 * receiving the error response before retrying.  If retrying requests also
 * fail, clients should use an exponential backoff scheme to gradually increase
 * the delay between retries based on `retry_delay`, until either a maximum
 * number of retries have been reached or a maximum retry delay cap has been
 * reached.
 */
final readonly class RetryInfo
{
    /**
     * @param ?\Google\Protobuf\Duration $retryDelay Clients should wait at least this long between retrying the same request.
     */
    public function __construct(
        #[Reflection\Field(1, new Reflection\ObjectT(\Google\Protobuf\Duration::class))]
        public ?\Google\Protobuf\Duration $retryDelay = null,
    ) {}
}
