<?php

/**
 * Code generated by thesis/protoc-plugin. DO NOT EDIT.
 * Versions:
 *   thesis/protoc-plugin — v0.1.19
 *   protoc               — v6.33.5
 * Source: google/rpc/status.proto
 */

declare(strict_types=1);

namespace Google\Rpc;

use Thesis\Protobuf\Reflection;

/**
 * @api
 *
 * The `Status` type defines a logical error model that is suitable for
 * different programming environments, including REST APIs and RPC APIs. It is
 * used by [gRPC](https://github.com/grpc). Each `Status` message contains
 * three pieces of data: error code, error message, and error details.
 *
 * You can find out more about this error model and how to work with it in the
 * [API Design Guide](https://cloud.google.com/apis/design/errors).
 */
final readonly class Status
{
    /**
     * @param int $code The status code, which should be an enum value of
     * [google.rpc.Code][google.rpc.Code].
     * @param string $message A developer-facing error message, which should be in English. Any
     * user-facing error message should be localized and sent in the
     * [google.rpc.Status.details][google.rpc.Status.details] field, or localized
     * by the client.
     * @param list<\Google\Protobuf\Any> $details A list of messages that carry the error details.  There is a common set of
     * message types for APIs to use.
     */
    public function __construct(
        #[Reflection\Field(1, Reflection\Int32T::T)]
        public int $code = 0,
        #[Reflection\Field(2, Reflection\StringT::T)]
        public string $message = '',
        #[Reflection\Field(3, new Reflection\ListT(new Reflection\ObjectT(\Google\Protobuf\Any::class)))]
        public array $details = [],
    ) {}
}
